### ISSUE TITLE
Move CI off Travis?

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/EXtra-data#102]
travis-ci.org is going away in favour of travis-ci.com, and while it's not exactly clear what's happening with open source projects on travis-ci.com, it's not encouraging. Capacity seems to be limited enough that backlogs build up, and it looks like the free credits for open source projects are either going to be much more limited, or will have to be manually requested.

I guess the easiest thing is to switch to Github actions, like [this example](https://github.com/European-XFEL/princess/blob/master/.github/workflows/test.yml). But I'm not 100% comfortable with how much everyone is centralising on Github, so if someone wants to play with another CI option, now's a good time. :slightly_smiling_face:

**Comment by takluyver** [comment]
E.g. the CI for PR #101 just took about 45 minutes to start because of a backlog that's still growing.

**Comment by RobertRosca** [comment]
Closed by #105
