### ISSUE TITLE
Method to get data from files into a single-source ZeroMQ stream

### ISSUE THREAD

**Issue by dallanto** [European-XFEL/EXtra-data#14]
A new branch "file_stack" was created, and a prototype script pushed to it.
If this is considered useful, a merge request for a method in export.py may follow.

**Comment by takluyver** [comment]
Thanks! I think this might be useful as an option for `karabo-bridge-serve-files`; it's a bit technically impure that we're pretending to be a karabo device, but as the combined detector data is a key use case for Karabo bridge, I think it makes sense to be able to present data from files in the same format that it comes online.

I'd be interested in @tmichela's thoughts too.

**Comment by tmichela** [comment]
Agreed with @takluyver , I would have it as an option of `serve-files`

**Comment by dallanto** [comment]
See pull requet "File stack" #40

**Comment by takluyver** [comment]
Done in #40 and #51.
