### ISSUE TITLE
Missing method `squeeze` for StackView

### ISSUE THREAD

**Issue by zhujun98** [European-XFEL/EXtra-data#15]
For raw modular detector data (`image.data`) the shape is (memory cell, 1, modules, y, x), which has an extra axis. If `stack_detector_modules` returns a true numpy array, `np.squeeze` will be needed (at least in `EXtra-foam`) to remove the extra axis. So we need to add a `squeeze` method for StackView, otherwise the code will fail at shape checking when a pre-allocated output array is used. 

As far as I remember, In the early version, `karabo_data` can deal with raw and calibrated data at the same time.

**Comment by takluyver** [comment]
Makes sense, and it turns out to be very easy (unless I've missed something). Have a look at #16.
