### ISSUE TITLE
Ensure virtual datasets are created with absolute paths

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/EXtra-data#21]
Using the `.write_virtual()` method with a run opened by a relative path, the virtual datasets point to relative paths, and can only be accessed when the working directory is the same. We should ensure we create the virtual datasets with absolute file paths to avoid this.

**Comment by egorsobolev** [comment]
Is it possible to set the search path for virtual dataset sources? It seems planed, see [RFC: HDF5 Virtual Dataset, section 5.5.5, page 23](https://portal.hdfgroup.org/download/attachments/50892982/HDF5-VDS-requirements-use-cases-2014-12-10.pdf)

**Comment by takluyver** [comment]
It's possible, but the code accessing them needs to do that. I think using absolute paths is a better solution.

The move towards closing and reopening files on demand also makes it important to use absolute paths - if the user changes the working directory, then reopening files by relative paths will no longer work.

**Comment by egorsobolev** [comment]
Yes, it's the simplest solution and completely valid for local set up. 
And it makes all stored VDS are not valid in the case of data relocation. For example, if we copy some data to gpfs for tests or examples. Users also may transfer data to other clusters. With absolute paths, they will have to regenerate all VDS. If we introduce an adjustable base location (e.g. root dir of an experiment), things become more flexible, they don't?

**Comment by takluyver** [comment]
I think this should now consistently use absolute paths, because `FileAccess` makes the path absolute. This is also important now that files can be closed and reopened by name - you don't want accessing data to break if you `cd`.

https://github.com/European-XFEL/EXtra-data/blob/5961f18c387114858a8265501c90db18488985b7/extra_data/file_access.py#L120-L121

We can continue discussing how else we might use virtual datasets, but I think it's easier to understand if a virtual dataset refers to source data in a single location, and you generate a separate file for data at another location. I kind of think virtual datasets have a lot of flexibility which you don't really want in most cases - they're cheap to create, so I'd rather create simple virtual datasets as needed and discard them readily rather than trying to make a more complex, flexible object.
