### ISSUE TITLE
Trim dependencies?

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/EXtra-data#210]
EXtra-data has a lot of dependencies when users install it in a fresh environment, and many of them are not strictly required.

- h5py & numpy are clearly required
- psutil is used in a couple of places - is there a sensible alternative to the `cpu_affinity()` method we use to see how many cores a process can use?
- karabo-bridge is only used for streaming data -> move it to a 'bridge' extra?
- matplotlib, pandas and xarray are all used by specific features; it's possible to read data without any of these. But some of those methods are quite important, e.g. `.get_array()`.
- We're aiming to drop the dependency on fabio soon anyway

cc @philsmt

**Comment by takluyver** [comment]
We could also consider removing the `QuickView` class - a simple 'frame switcher' for showing images with matplotlib. It has hardly been changed since 2017, which means either it's a triumph of elegant simplicity, or it's hardly getting used.

On the other hand, matplotib is so widely used that there may not be much point avoiding a dependency on it.

**Comment by takluyver** [comment]
I think we can replace psutil's `cpu_affinity()` method with [`os.sched_getaffinity()`](https://docs.python.org/3.6/library/os.html#os.sched_getaffinity).

It looks like the stdlib function is Unix only, whereas psutil has a Windows implementation for it. But EXtra-data probably isn't used that much on Windows, so I think we can fall back to something like `min(os.cpu_count(), 4)`.

**Comment by cydanil** [comment]
I think it's probably safe to remove `matplotlib`.  
It's only used with the `docs/xpd_examples` notebooks and within `extra_data/utils.py` [for the `QuickView` class](https://github.com/European-XFEL/EXtra-data/blob/master/extra_data/utils.py#L21), which I have a feeling isn't used (and could be deprecated?)

**Comment by takluyver** [comment]
We got rid of the matplotlib dependency as well. The remaining direct dependencies are h5py, numpy, pandas and xarray. The last two could strictly be made optional, but they're familiar packages and used in some highly visible methods that are highlighted in example docs, so I'm inclined to leave them as full dependencies.

There's some discussion in Python packaging about a way to have optional dependencies that are installed by default. If that does happen, we might make use of it.
