### ISSUE TITLE
Can't instantiate multi-module detector access if any module has no data

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/EXtra-data#221]
This happens a lot with LPD data. It looks like the root cause is a problem with `.data_counts()`.

```python
run = open_run(2729, 44)
LPD1M(run.select_trains(np.s_[:100])
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-fb113b52e6e9> in <module>
----> 1 LPD1M(run_trains, parallel_gain=True)

~/Code/EXtra-data/extra_data/components.py in __init__(self, data, detector_name, modules, min_modules, parallel_gain)
   1210     def __init__(self, data: DataCollection, detector_name=None, modules=None,
   1211                  *, min_modules=1, parallel_gain=False):
-> 1212         super().__init__(data, detector_name, modules, min_modules=min_modules)
   1213 
   1214         self.parallel_gain = parallel_gain

~/Code/EXtra-data/extra_data/components.py in __init__(self, data, detector_name, modules, min_modules)
    393     def __init__(self, data: DataCollection, detector_name=None, modules=None,
    394                  *, min_modules=1):
--> 395         super().__init__(data, detector_name, modules, min_modules=min_modules)
    396 
    397     @staticmethod

~/Code/EXtra-data/extra_data/components.py in __init__(self, data, detector_name, modules, min_modules)
    116         mod_data_counts = pd.DataFrame({
    117             src: data.get_data_counts(src, self._main_data_key)
--> 118             for src in source_to_modno
    119         }).fillna(0).astype(np.uint64)
    120 

~/Code/EXtra-data/extra_data/components.py in <dictcomp>(.0)
    116         mod_data_counts = pd.DataFrame({
    117             src: data.get_data_counts(src, self._main_data_key)
--> 118             for src in source_to_modno
    119         }).fillna(0).astype(np.uint64)
    120 

~/Code/EXtra-data/extra_data/reader.py in get_data_counts(self, source, key)
    442             Key of parameter within that device, e.g. "image.data".
    443         """
--> 444         return self._get_key_data(source, key).data_counts()
    445 
    446     def get_series(self, source, key):

~/Code/EXtra-data/extra_data/keydata.py in data_counts(self, labelled)
    149         IDs. Otherwise, returns a NumPy array of counts to match ``.train_ids``.
    150         """
--> 151         train_ids = np.concatenate([c.train_ids for c in self._data_chunks])
    152         counts = np.concatenate([c.counts for c in self._data_chunks])
    153 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate
```

**Comment by thari44** [comment]
> This happens a lot with LPD data. It looks like the root cause is a problem with `.data_counts()`.
> 
> ```python
> run = open_run(2729, 44)
> LPD1M(run.select_trains(np.s_[:100])
> ```
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-12-fb113b52e6e9> in <module>
> ----> 1 LPD1M(run_trains, parallel_gain=True)
> 
> ~/Code/EXtra-data/extra_data/components.py in __init__(self, data, detector_name, modules, min_modules, parallel_gain)
>    1210     def __init__(self, data: DataCollection, detector_name=None, modules=None,
>    1211                  *, min_modules=1, parallel_gain=False):
> -> 1212         super().__init__(data, detector_name, modules, min_modules=min_modules)
>    1213 
>    1214         self.parallel_gain = parallel_gain
> 
> ~/Code/EXtra-data/extra_data/components.py in __init__(self, data, detector_name, modules, min_modules)
>     393     def __init__(self, data: DataCollection, detector_name=None, modules=None,
>     394                  *, min_modules=1):
> --> 395         super().__init__(data, detector_name, modules, min_modules=min_modules)
>     396 
>     397     @staticmethod
> 
> ~/Code/EXtra-data/extra_data/components.py in __init__(self, data, detector_name, modules, min_modules)
>     116         mod_data_counts = pd.DataFrame({
>     117             src: data.get_data_counts(src, self._main_data_key)
> --> 118             for src in source_to_modno
>     119         }).fillna(0).astype(np.uint64)
>     120 
> 
> ~/Code/EXtra-data/extra_data/components.py in <dictcomp>(.0)
>     116         mod_data_counts = pd.DataFrame({
>     117             src: data.get_data_counts(src, self._main_data_key)
> --> 118             for src in source_to_modno
>     119         }).fillna(0).astype(np.uint64)
>     120 
> 
> ~/Code/EXtra-data/extra_data/reader.py in get_data_counts(self, source, key)
>     442             Key of parameter within that device, e.g. "image.data".
>     443         """
> --> 444         return self._get_key_data(source, key).data_counts()
>     445 
>     446     def get_series(self, source, key):
> 
> ~/Code/EXtra-data/extra_data/keydata.py in data_counts(self, labelled)
>     149         IDs. Otherwise, returns a NumPy array of counts to match ``.train_ids``.
>     150         """
> --> 151         train_ids = np.concatenate([c.train_ids for c in self._data_chunks])
>     152         counts = np.concatenate([c.counts for c in self._data_chunks])
>     153 
> 
> <__array_function__ internals> in concatenate(*args, **kwargs)
> 
> ValueError: need at least one array to concatenate
> ```
