### ISSUE TITLE
Provide a means to access RUN data

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/EXtra-data#26]
RUN stores a single value from each control data field, for the start of the run. This is duplicated in all the sequence files, but it still contains the data from the start of the *run*, not the start of that file, if I've understood correctly.

Previously we ignored this, because all the same data was in CONTROL anyway. Now it's possible to mark fields as omitted, in which case they won't be stored under CONTROL, but they will still have a snapshot in RUN.

This is low priority for now, because I imagine that the data people are interested in will still be recorded in CONTROL. It can be re-prioritised if we hear about a use case that needs it.

**Comment by tmichela** [comment]
Also, RUN contains a snapshot of all properties of all devices stored in the run. The CONTROL section might (will) contain only a selection of properties (set with the DAQ policy).
Also string properties are not stored in CONTROL

**Comment by fangohr** [comment]
I imagine this could be useful. 

While inspecting fast data or CONTROL data from the file, the question may arise about the value of some other parameter during this run.

**Comment by takluyver** [comment]
We have now had a request for this from HED. For example, run `/gpfs/exfel/exp/HED/202022/p002702/raw/r0173/`, sources `hed_exp_ibs_cam_cam` on DA07 (named not following convention) and `HED_OPT_PAM/CAM/SAMPLE_CAM_4` on DA06, both have a `triggerMode` string in RUN which it's not saved in CONTROL. Apparently this should not change during a run, so it makes sense to access it as a single value for the whole run.
