### ISSUE TITLE
Add option to easily suppress stderr printouts when loading aliases in `open_run`

### ISSUE THREAD

**Issue by bj-s** [European-XFEL/EXtra-data#476]
When opening runs with aliases files, this produces a print to stderr that informs about the loaded aliases (see `extra_data.reader.open_run`). 

e.g. `Loading 278 aliases from: /gpfs/exfel/exp/[...]/usr/extra-data-aliases.yml`

For me, this message turns out to be very annoying particularly when opening many runs. It would be great if this message could be suppressed easily. Therefore, I think one could make it a warning (so people can use warnings.filterwarnings) or have a flag to suppress this.

In the following, a possible work around that can be used right now. However, I think it should not be that complicated to suppress this message:
```python
import sys
import contextlib
import extra_data as xd

# based on reply in https://stackoverflow.com/questions/34904946/how-to-filter-stdout-in-python-logging
class StdFilter(object):
    def __init__(self, strings_to_filter, stream):
        self.stream = stream
        self.strings_to_filter = strings_to_filter
        self.triggered = False

    def __getattr__(self, attr_name):
        return getattr(self.stream, attr_name)

    def write(self, data):
        for string in self.strings_to_filter:
            if string in data:
                self.triggered = True
                self.stream.flush()
                return None
            
        if self.triggered:
            self.triggered = False
            if data=="\n":
                self.stream.flush()
                return None
            
        self.stream.write(data)
        self.stream.flush()

    def flush(self):
        self.stream.flush()
        
stderr_filter = StdFilter([" aliases from: "], sys.stderr)
        
with contextlib.redirect_stderr(stderr_filter):
    r = xd.open_run(4098, 199)

```

**Comment by takluyver** [comment]
Thanks, I agree that there should be an easier way to suppress that message than the code you showed.

I don't think making it a warning is a great solution. Loading aliases isn't a problem, so it's not semantically a warning, and while filtering warnings is simpler than what you show, it's still pretty inconvenient.

I think the best thing is to convert it to a logging message and ensure it's hidden by default. We already use logging in a handful of places in EXtra-data, e.g.

https://github.com/European-XFEL/EXtra-data/blob/d18ead4a3dc566150ee3617a99366a467010a610/extra_data/read_machinery.py#L262

https://github.com/European-XFEL/EXtra-data/blob/d18ead4a3dc566150ee3617a99366a467010a610/extra_data/reader.py#L1841-L1842

By default, debug and info messages aren't shown (but warning & higher levels are). This can obviously be configured, either setting a different threshold globally or getting into much more detail.

I don't recall why we thought it was important to make a visible message for this, though, and the discussion on #398 isn't very clear to me now - perhaps we had agreed in a separate conversation that it should be visible. @philsmt @JamesWrigley do you remember?

**Comment by JamesWrigley** [comment]
Sadly my memory is going in my old age :pensive: But I think the motivation was just to make people aware that aliases were loaded without having to notice them in `run.info()` or manually checking `run.aliases`. I'd say we can remove that message entirely if it's annoying.

**Comment by philsmt** [comment]
I think the concern was related to unexpected behaviour with the aliases loaded by default and the user not knowing about it. Say you go ahead and define some custom aliases at runtime, an exception might be thrown for conflicts between automatically defined aliases and new ones.

In all fairness though, this might be a rather far-fetched scenario. If the easy warning put in now is annoying and we still feel strongly about it, one might extend the exception raised on conflicts in the presence of automatic aliases.

**Comment by takluyver** [comment]
It sounds like none of us strongly feel like the message needs to be visible, so I've opened #478 to do it through logging, which should mean it's invisible by default.
