### ISSUE TITLE
Write newer data format version in voview files

### ISSUE THREAD

**Issue by philsmt** [European-XFEL/EXtra-data#487]
voview files are currently writing EXDF-v0.5, which in particular does not contain various fields in `METADATA`. Calibration code has started to use these fields for newer detectors for which there should never be EXDF-v0.5 files, breaking it.

**Comment by philsmt** [comment]
Alternatively, `DataCollection.run_metadata()` should use `.data_files` rather than `.files`.

**Comment by philsmt** [comment]
Uhm.

:see_no_evil: 

And here I was convinced 5 minutes ago it still doesn't in `master`.

**Comment by JamesWrigley** [comment]
TBF, it's still possible for this to occur if someone's running a RunValidator pointing to an environment with an old extra-data version (happened last week at FXE).

**Comment by takluyver** [comment]
I've opened an MR to update the default Python environment used by RunValidator - hopefully that will make such occurrences less likely. It would have prevented my mistake at FXE.
