### ISSUE TITLE
Objects for individual sources or datasets?

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/EXtra-data#55]
The `DataCollection` object is the centrepiece of EXtra-data, and has a tendency to keep growing. Many of its methods take `source, key` parameters to refer to a specific dataset, e.g. `get_array()` or `get_data_counts()`. There are others possible - e.g. how do you find the dtype or entry shape for a given key? A couple take just `source`, e.g. `keys_for_source()`.

Should we add new types to represent an individual source or an individual dataset in the available data? That would allow APIs maybe like this:

```python
run.keys_for_source("SA3_XTD10_PES/ADC/1:network")  # Current
run["SA3_XTD10_PES/ADC/1:network"].keys()  # Hypothetical

# Current:
run.get_array("SA3_XTD10_PES/ADC/1:network", "digitizers.channel_4_A.raw.samples")
# Hypothetical:
run["SA3_XTD10_PES/ADC/1:network", "digitizers.channel_4_A.raw.samples"].get_array()
```

And it would give a convenient place to expose things like the dtype & entry shape of a key, without awkward methods on DataCollection.

My reservations are:

- Do more classes make it harder to understand? I recall that one of the original goals was to use basic data structures like dicts as far as possible.
- The naming challenge - I've referred to 'sources' and 'datasets' here, but e.g. 'dataset' already means one thing in HDF5 and a different thing in Xarray, so that's not a great name. 'Source' also has many meanings, although not so immediately adjacent.

@tmichela @philsmt & anyone else who's interested: thoughts? This is for discussion at the moment, I'm not asking anyone to start coding.

**Comment by philsmt** [comment]
Oh, that is beautiful.

As a matter of fact, I encountered this issue in my mapAPI-experiments (#32) for determining the dtype just as you describe. Furthermore, there are slight discrepancies in the naming and possible inputs already, notwithstanding the complex machinery behind wildcard matching and possible types in the select*() calls.

Indexing could make the API much more straightforward and clear in what you mean by a particular source, i.e. applying to a source as a whole, several sources by wildcard or list, keys... one might add even train slices (and at some point pulse slices) as a third tuple component. I may be too enthusiastic here whether this can be implemented all the way like I'm dreaming of it right now, but using indexing might result in a beautiful Pythonic API that "just works". But I'm a romantic when it comes to expressive APIs hiding boilerplate behind operators.

I don't see a particular issue with naming as we should stick to Karabo terms, i.e. "source" and "key". However, it may be difficult for an inexperienced programmer to understand the capabilities his current "index" has. Is it a source? A key? Several sources and one key? The current API is inflexible, but states it somewhat clearly in its reference. We should probably try to start with an exhaustive list of objects and calls to find any pitfalls.

A few additional ideas from the top of my head:
- select by indexing
`subrun = run['*UTC1/ADC*', '*.channel_1_*.raw.samples']`
`subrun = run['*', '*', by_id[:100]]`
- emulating the Karabo hash, i.e. allow partial access into keys and return dict of arrays
`run['SA3_XTD10_XGM/XGM/DOOCS:output', 'data'].get_xarray()`
- crazy moonshot on the verge of too much: some objects could be `array_like`
`run['SA3_XTD10_XGM/XGM/DOOCS:output', 'data.intensitySa3TD'].mean(axis=0)[:10]`

**Comment by egorsobolev** [comment]
I would say there are already objects like *dataset*. They even cached in iterators. Just the functionality is not encapsulated in the proper class.

I also feel the absence of proper *dataset* class in #47.

Object oriented approach shouldn't make it harder to understand.

**Comment by takluyver** [comment]
Thanks!

I was avoiding 'key' as a name because, as I see it, the key is the string identifying some data, not the data itself. In the context of a mapping, the counterpart is called the 'value', but that suggests a single number as opposed to an array.

I'd be reluctant to add those extra features:

- Wildcards would mean returning different types based on non-obvious features of the keys - e.g. if a wildcard pattern only matches one source, do you return a DataCollection like `.select()`, or treat it like a precise name was specified?
- Selecting trains: maybe, but I prefer an explicit API for that. We could make accessor attributes, e.g. `run.by_trains[:100]` if `.select_trains()` is too verbose.
- Partial indexing: same objection about returning different types, but now it's even less obvious for unfamiliar devices - is `'data'` a complete or partial key? The ability to get a dict of arrays - or an xarray Dataset - could be useful, though.
- Array like objects: I can see the temptation, but which array API: plain numpy, Xarray, Dask? More concretely, would you expect `.mean()` to work on data that won't fit in memory? I think having an explicit 'load this into an array' step is worth forcing people to write slightly more verbose code. I'm also informed by h5py here: datasets allow slicing to load data as an array, but deliberately don't expose all the array methods directly, because it's not clear what it would mean.

**Comment by tmichela** [comment]
> Do more classes make it harder to understand? I recall that one of the original goals was to use basic data structures like dicts as far as possible.

The reason behind that, was to have the data structure to look similar to the data in karabo. But that specific to the case when one reads data  train by train. With this new class, the use case is different since we aim at access data across multiple trains.

> The naming challenge - I've referred to 'sources' and 'datasets' here, but e.g. 'dataset' already means one thing in HDF5 and a different thing in Xarray, so that's not a great name. 'Source' also has many meanings, although not so immediately adjacent.

I think `DataSet` makes the most sens, but I understand that it can cause confusion with what it means in other libraries...
Something like `DataSource` maybe? I think that's how it's called in psana
`SourceDataSet`?

**Comment by takluyver** [comment]
OK, it seems that we're all broadly OK with doing something like this. So, making things more specific:

1. I think the most obvious missing piece is an object representing data from one key of one source, which could be loaded into one array. What should this be called? I suggested 'dataset' initially, but we've discussed the problems with this. How about `KeyData`?
2. Are we happy with the indexing-style syntax `run[source, key]` to make one of these objects from a `DataCollection`?
3. Do we also want to add another type for a single source with multiple keys, in between `DataCollection` (many sources) and the new single key object? I can see some uses for this, but not as many, so I'm inclined to add just the single key object for now and see how people get on with that.

**Comment by egorsobolev** [comment]
Some classes may be designed for the inernal usage. A single source seems asking for an individual class, since each source has its own index, and type (instrument or control). Such class (e.g. `Source`) allows to encapsulate these data and corresponded operations and avoid their duplication in the grained type (`KeyData`).

**Comment by philsmt** [comment]
I'd suggest trying to stay as close to Karabo as possible and avoiding hdf terms. `KeyData` sounds like a great compromise in that regard.

If we keep this object stateless, we could ensure there's only one instance for any given `source, key` combination of a `DataCollection`, e.g. by overwriting `__new__`. I don't see any particular reason for it have some internal state beyond the `source` and `key` it's referring to, except maybe some caching behaviour. If it should support iteration, we can create a new corresponding iterator object in `__iter__`.

It makes sense to go one interface at a time. Your initial suggestion is probably the strongest point, as we can expose so many properties (literally as properties) with it. Quite frankly, yes, we should think hard about expanding it further (as I might've hinted by my first comment), but it should probably be well thought-out.

Oh, and can we please distinguish between `ndarray` and `xarray` this time ;-P
While I became a huge fan of `xarray` recently for coordinates and annotations, we should make this explicit.

**Comment by takluyver** [comment]
OK, we'll start with `KeyData`, but we'll probably want to add `Source` (`SourceData` for symmetry?) before long. I'm on board with making it stateless - `DataCollection` is already designed to be basically stateless.

I'm inclined to make anything which actually loads the full data a method (`k.xarray()`) rather than a property (`k.xarray`), because I think the call syntax is a useful hint that there's work involved, and this is not necessarily a cheap operation. I'm more open to it for things that could use cached metadata & indexes, e.g. `k.dtype`.

Yes, with the benefit of hindsight, maybe I pushed xarray a bit too hard. The idea was that you can always get the numpy array out (`arr.data`) if that's what you need, and the labels are useful often enough that they should be there by default. I'm OK with having e.g. `.xarray()` and `.ndarray()`, but I'd still like to avoid that `.array()` gives you an unlabelled array, because I know how readily people take a more convenient option, even when the difference is tiny (like `ipython3` vs `ipython`).
