### ISSUE TITLE
Make virtual file: configurable fill value for missing data

### ISSUE THREAD

**Issue by tmichela** [European-XFEL/EXtra-data#58]
Currently when making virtual hdf5 files, the fill value for missing data is `np.nan`. Some software do not play nicely with NANs (Crystfel? where peaks are found with nan intensities), we should add the option to chose the fill value.

**Comment by takluyver** [comment]
Seems reasonable. I wonder if we need to allow setting it for each dataset independently?

**Comment by tmichela** [comment]
Hum, good point. I guess for `data`, one would usually want to set the default value to 0. But for `mask` or `gain` it may make sens to have other values.

**Comment by dallanto** [comment]
Yes, I think if we set ``data`` to 0 we might want to set ``mask`` to ``!= 0``, to indicate unusual pixels. Ideally programs like CrystFEL would then ignore such non-existing, filled modules in the first place.
