### ISSUE TITLE
Issue with writing subsets of AGIPD data to new file

### ISSUE THREAD

**Issue by reiserm** [European-XFEL/EXtra-data#80]
I tried to use the `AGIPD1M.write_frames()` method to write a subset of processed data to a new HDF5 file

`agp = AGIPD1M(run, min_modules=16)`
`agp.write_frames('test.h5', np.array(run.train_ids[10:20]), np.ones(10))`

This causes the following h5py error:

`ValueError: Chunk shape must not be greater than data shape in any dimension. (4096,) is not compatible with (0,)`

**Comment by takluyver** [comment]
Thanks Mario. I guess one of the modules has no data in that selection, so it's trying to write an empty dataset. I'll get on this.

**Comment by takluyver** [comment]
Can I ask you to post the traceback or the path of a run so I can reproduce it? I tried to write a test, but so far it's passing.

**Comment by reiserm** [comment]
In [4]: run = RunDirectory("/gpfs/exfel/exp/MID/202022/p002693/proc/r0087/")

In [5]: agp = AGIPD1M(run, min_modules=16)

In [6]: agp.write_frames('test.h5', np.array(run.train_ids[10:20]), np.ones(10))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-955159130720> in <module>
----> 1 agp.write_frames('test.h5', np.array(run.train_ids[10:20]), np.ones(10))

/gpfs/exfel/u/scratch/MID/202022/p002693/reiserm/.venv/lib64/python3.6/site-packages/extra_data/components.py in write_frames(self, filename, trains, pulses)
    444         writer = FramesFileWriter(filename, self.data, inc_tp_ids)
    445         try:
--> 446             writer.write()
    447         finally:
    448             writer.file.close()

/gpfs/exfel/u/scratch/MID/202022/p002693/reiserm/.venv/lib64/python3.6/site-packages/extra_data/writer.py in write(self)
    133
    134         for source in d.all_sources:
--> 135             self.prepare_source(source)
    136
    137         self.write_metadata()

/gpfs/exfel/u/scratch/MID/202022/p002693/reiserm/.venv/lib64/python3.6/site-packages/extra_data/writer.py in prepare_source(self, source)
     27             src_ds1 = self.data._source_index[source][0].file[path]
     28             self.file.create_dataset_like(
---> 29                 path, src_ds1, shape=(nentries,) + src_ds1.shape[1:],
     30             )
     31             if source in self.data.instrument_sources:

/gpfs/exfel/u/scratch/MID/202022/p002693/reiserm/.venv/lib64/python3.6/site-packages/h5py/_hl/group.py in create_dataset_like(self, name, other, **kwupdate)
    236             kwupdate.setdefault('maxshape', other.maxshape)
    237
--> 238         return self.create_dataset(name, **kwupdate)
    239
    240     def require_group(self, name):

/gpfs/exfel/u/scratch/MID/202022/p002693/reiserm/.venv/lib64/python3.6/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    134
    135         with phil:
--> 136             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    137             dset = dataset.Dataset(dsid)
    138             if name is not None:

/gpfs/exfel/u/scratch/MID/202022/p002693/reiserm/.venv/lib64/python3.6/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl)
    102         errmsg = "Chunk shape must not be greater than data shape in any dimension. "\
    103                  "{} is not compatible with {}".format(chunks, shape)
--> 104         raise ValueError(errmsg)
    105
    106     if isinstance(dtype, Datatype):

ValueError: Chunk shape must not be greater than data shape in any dimension. (4096,) is not compatible with (0,)

**Comment by takluyver** [comment]
Thanks!

**Comment by takluyver** [comment]
#82 should fix this.
